### ISSUE TITLE
Patch release for xcode 7.3 fix?

### ISSUE THREAD

**Issue by brennantaylor** [SlatherOrg/slather#173]
Looks like a fix was merged in for xcode 7.3.

Can we get a release to resolve this issue?

**Comment by palusik86** [comment]
+1 did stop working.

**Comment by bwised** [comment]
+1 for me.  I have a ton of build server jobs that are totally hosed right now.

**Comment by ksuther** [comment]
I've made additional Xcode 7.3 fixes in #174, you might try that out if you're willing to build and install the gem manually (`gem build slather.gemspec && gem install slather-2.0.1.gem`).

**Comment by themackworth** [comment]
You can use a Gemfile like this:

1)Install bundler
2) Create a Gemfile that contains `gem 'slather', :git => 'git://github.com/SlatherOrg/slather', ref: '36ee7ec02bd7f372020e4234981f7024e5e15739'`
3) run `bundle install`
4) run slather by running `bundle exec slather ...`

**Comment by brennantaylor** [comment]
Thanks @ksuther @themackworth

**Comment by K76154** [comment]
This still fails with the following error. It looks like it is looking for iOS 9.2 simulator SDK instead of the latest 9.3:

error: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h: No such file or directory
error: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/include/MacTypes.h: No such file or directory
error: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/include/objc/objc.h: No such file or directory
error: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/include/sys/_types.h: No such file or directory
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include/stdarg.h: No such file or directory
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include/stddef.h: No such file or directory
/Users/administrator/.bundler/ruby/2.0.0/slather-36ee7ec02bd7/lib/slather/coverage_info.rb:74:in `realpath': No such file or directory - /Users/administrator/.bundler/ruby/2.0.0/slather-36ee7ec02bd7/warning The file ' (Errno::ENOENT)

**Comment by ksuther** [comment]
It may be finding leftover coverage from Xcode 7.2. Try deleting your DerivedData directory and run everything again.

**Comment by neonichu** [comment]
I'll make a new release sometime this week, once #174 has been merged as well.

**Comment by palusik86** [comment]
Looking forward for it :-)

**Comment by neonichu** [comment]
2.0.2 has just been released: https://github.com/SlatherOrg/slather/releases/tag/v2.0.2
